CREATE DATABASE IF NOT EXISTS alx_book_store;
  
	CREATE TABLE Authors(Author_ID INT PRIMARY KEY,
	AUTHOR_NAME VARCHAR(215));
    
    CREATE TABLE BOOKS(BOOK_ID INT PRIMARY KEY,
	TITLE VARCHAR(130),AUTHOR_ID INT ,PRICE DOUBLE , PUBLICATION_DATE DATE);
 
	alter table Authors RENAME COLUMN AUTHOR_ID TO author_id;
	alter table Authors RENAME COLUMN AUTHOR_NAME TO author_name;
	SELECT * FROM AUTHORS; 

	ALTER TABLE BOOKS ADD FOREIGN KEY 
	(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID);

	SELECT * FROM BOOKS;
	 

	SHOW CREATE TABLE BOOKS;

	CREATE TABLE CUSTOMERS(CUSTOMER_ID INT PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(215), EMAIL VARCHAR(215),
	ADDRESS TEXT);
	 
	CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY, CUSTOMER_ID INT,
	ORDER_DATE DATE);

	ALTER TABLE ORDERS ADD FOREIGN KEY 
	(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID);

	 

	CREATE TABLE ORDER_DETAILS(
	ORDERDETAILID INT PRIMARY KEY,
	ORDER_ID INT, BOOK_ID INT , QUANTITY DOUBLE);

	ALTER TABLE ORDER_DETAILS ADD FOREIGN KEY (ORDER_ID)
	REFERENCES ORDERS(ORDER_ID);
	 
	ALTER TABLE ORDER_DETAILS ADD FOREIGN KEY (BOOK_ID)
	REFERENCES BOOKS(BOOK_ID);

	ALTER TABLE BOOKS ADD FOREIGN KEY 
	(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID);
	SELECT * FROM BOOKS;

select * from books;
select * from authors;
