CREATE DATABASE IF NOT EXISTS alx_book_store;
  
	CREATE TABLE Authors(author_id INT PRIMARY KEY,
	AUTHOR_NAME VARCHAR(215));
    
    CREATE TABLE Books(book_id INT PRIMARY KEY,
	title VARCHAR(130),author_id INT ,price DOUBLE , publication_date DATE);
 
 
 
	ALTER TABLE BOOKS ADD FOREIGN KEY 
	(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID);

 
	 

 

	CREATE TABLE CUSTOMERS(customer_id INT PRIMARY KEY,
	customer_name VARCHAR(215), email VARCHAR(215),
	address TEXT);
	 
	CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY, CUSTOMER_ID INT,
	ORDER_DATE DATE);

	ALTER TABLE ORDERS ADD FOREIGN KEY 
	(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID);

	 

	CREATE TABLE ORDER_DETAILS(
	ORDERDETAILID INT PRIMARY KEY,
	ORDER_ID INT, BOOK_ID INT , QUANTITY DOUBLE);

	ALTER TABLE ORDER_DETAILS ADD FOREIGN KEY (ORDER_ID)
	REFERENCES ORDERS(ORDER_ID);
	 
	ALTER TABLE ORDER_DETAILS ADD FOREIGN KEY (BOOK_ID)
	REFERENCES BOOKS(BOOK_ID);

	ALTER TABLE BOOKS ADD FOREIGN KEY 
	(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID);
	SELECT * FROM BOOKS;

select * from books;
select * from authors;
